#!/usr/bin/bash

pin1=14
pin2=15
pin3=18
pin4=23

pinctrl set $pin1 op
pinctrl set $pin2 op
pinctrl set $pin3 op
pinctrl set $pin4 op

while true; do
	for i in {0..7}; do
		pinctrl set $pin2 dl
		pinctrl set $pin3 dl
		pinctrl set $pin4 dl
		if(( (i/1)%2));then
			pinctrl set $pin4 dh
		fi
		if(( (i/2)%2));then
			pinctrl set $pin3 dh
		fi
		if(( (i/4)%2));then
			pinctrl set $pin2 dh
		fi
		sleep 1
	done
done

