#!/usr/bin/bash

pin1=23
pin2=18
pin3=15

pinctrl set $pin1 op	
pinctrl set $pin2 op
pinctrl set $pin3 op

while true; do
	for i in {0..7}; do
		pinctrl set $pin1 dl
		pinctrl set $pin2 dl
		pinctrl set $pin3 dl
		[[ $((i%2)) -eq 1 ]] && pinctrl set $pin1 dh
		[[ $(((i/2)%2)) -eq 1 ]] && pinctrl set $pin2 dh
		[[ $(((i/4)%2)) -eq 1 ]] && pinctrl set $pin3 dh
		sleep 1
	done
done