#!/usr/bin/bash

pins=(14 15 18 23)

for pin in "${pins[@]}"; do
	pinctrl set "$pin" op
	pinctrl set "$pin" dl
done


while true; do
	for pin in "${pins[@]}"; do
		pinctrl set "$pin" dh
		sleep 1
		pinctrl set "$pin" dl
	done
done